<a href="https://colab.research.google.com/github/jbsurban7/Linear-Algebra-58020/blob/main/Determinant_of_a_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) #Initialization of the array
B = np.linalg.det(A) #Command to find the determinant of the given array
print(A)
print(B)
print(round(B)) #Rounded form of the original answer

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
