<a href="https://colab.research.google.com/github/jbsurban7/Linear-Algebra-58020/blob/main/FinalExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy.linalg import eig

Problem 1

In [7]:
C = 19

A = (C - 6)
B = (C * 3)
C = C

print("Student A has",A)
print("Student B has",B)
print("Student C has",C)

Student A has 13
Student B has 57
Student C has 19


**Problem 2**

In [6]:
import numpy as np
from scipy import linalg

A = np.array([3,-1,1],[9,-3,3],[-12,4,-4])
print(A)

B = np.array([[5,15,-20]])
print("")

B = B.T
print(B)

X = linalg.solve(A,B)
print(X)

TypeError: ignored

Problem 3

In [5]:
A= np.array ([[8,5,-6],[-12,-9,-12],[-3,-3,5]])
print(A)
print("")

b,c = np.linalg.eig(A)
print ("The eigenvalue/s is/are",b)
print ("The eigenvectors are:",c)
print("")
x = c.round()
print(x)

[[  8   5  -6]
 [-12  -9 -12]
 [ -3  -3   5]]

The eigenvalue/s is/are [-8.11684397  3.          9.11684397]
The eigenvectors are: [[ 2.35632155e-01 -7.07106781e-01 -8.61671223e-01]
 [-9.57707415e-01  7.07106781e-01  2.99299241e-01]
 [-1.65148399e-01 -1.19155502e-16  4.09808086e-01]]

[[ 0. -1. -1.]
 [-1.  1.  0.]
 [-0. -0.  0.]]
