<a href="https://colab.research.google.com/github/jbsurban7/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Question 1**

In [14]:
A = np.eye(5)

print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Question 2**

In [6]:
B = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])

print(B)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


**Question 3**

In [17]:
C = np.array([[1,2,6],[2,8,4],[6,4,5]])

print(C)

[[1 2 6]
 [2 8 4]
 [6 4 5]]


**Question 4**

In [19]:
D = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(D)
print(np.linalg.det(D))
print(round(np.linalg.det(D)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


**Queston 5**

In [25]:
E = np.array([[1,2,3],[2,3,3],[3,4,-2]])

print(E)

detE = np.linalg.det(E)
print(" ")
print("Determinant")
print(" ")
print(detE)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
 
Determinant
 
5.000000000000001


**Question 6**

In [26]:
F = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]])

print(F)

sqrtF = np.sqrt(F)
print(" ")
print("Roots")
print(" ")
print(sqrtF)

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]
 
Roots
 
[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
