# Problem 1

In [5]:
import numpy as np

In [12]:
w = np.array([[1, -3,0],[2,-2,0],[3,1,0]])
x = np.array([[3,2,1],[-1,2,3],[2,1,-1]])
y = np.array([[1,2,0],[0,-1,2],[0,0,0]])
z = np.array([[0,1],[2,3]])

In [14]:
#A
output=np.dot(w,y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [16]:
#B
output=np.add(z,z)
print(output)

[[0 2]
 [4 6]]


In [18]:
#C
output=np.dot(3,x)
print(output)

[[ 9  6  3]
 [-3  6  9]
 [ 6  3 -3]]


# Problem 2

In [24]:
#A The product (YW)2 is not defined
ans1=np.cross(y,w)

ans2= 2*ans1
print(ans2)

#A is false

[[  0   0 -10]
 [  8   8   4]
 [  0   0   0]]


In [28]:
#B WY – X = 
b1=np.dot(w,y)
b2=np.subtract(b1,x)

print(b2)

#B is false

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  4  3]]


In [37]:
#C

c1=np.dot(y,w)
c2=2*z

c1=([[5,-7],[4,4]])

c3=np.subtract(c1,c2)

print(c3)

#C is true

[[ 5 -9]
 [ 0 -2]]
