<a href="https://colab.research.google.com/github/jbsurban7/Linear-Algebra-58020/blob/main/Prelim%20Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### **Question 1**

In [10]:
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question 2**

In [11]:
doub = np.multiply(2,C)
print(doub)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


**Question 3**

In [17]:
a = np.array([2,7,4])
b = np.array([3,9,8])

q3 =np.cross(a,b)

print(q3)

[20 -4 -3]
