<a href="https://colab.research.google.com/github/jbsurban7/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
a = np.array([[-5,0],[4,1]])
print(a)

[[-5  0]
 [ 4  1]]


In [7]:
b = np.array([[6,-3],[2,3]])
print(b)

[[ 6 -3]
 [ 2  3]]


In [8]:
print(b-b)

[[0 0]
 [0 0]]
